import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav style={{
          width: '100%',
          background: '#fff',
          borderBottom: '1px solid #eee',
          padding: '0.5rem 0',
          marginBottom: 24,
          position: 'sticky',
          top: 0,
          zIndex: 100
        }}>
          <div style={{maxWidth: 1200, margin: '0 auto', display: 'flex', gap: 24, alignItems: 'center', justifyContent: 'flex-end', padding: '0 1rem'}}>
            <a href="/" style={{fontWeight: 500, color: '#222', textDecoration: 'none'}}>דף הבית</a>
            <a href="/about" style={{fontWeight: 500, color: '#222', textDecoration: 'none'}}>אודות</a>
            <a href="/articles" style={{fontWeight: 500, color: '#222', textDecoration: 'none'}}>מאמרים</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
